twig:
    default_path: '%kernel.project_dir%/templates'
    auto_reload: true
    form_themes:
        - bootstrap_3_layout.html.twig
    paths:
        '%kernel.project_dir%/public/assets/images': images

when@test:
    twig:
        strict_variables: true
